// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.2
// source: proto/scraper.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetricRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID    string  `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	MType string  `protobuf:"bytes,2,opt,name=MType,proto3" json:"MType,omitempty"`
	Delta int64   `protobuf:"varint,3,opt,name=Delta,proto3" json:"Delta,omitempty"`
	Value float64 `protobuf:"fixed64,4,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *MetricRequest) Reset() {
	*x = MetricRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_scraper_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetricRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricRequest) ProtoMessage() {}

func (x *MetricRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricRequest.ProtoReflect.Descriptor instead.
func (*MetricRequest) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{0}
}

func (x *MetricRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *MetricRequest) GetMType() string {
	if x != nil {
		return x.MType
	}
	return ""
}

func (x *MetricRequest) GetDelta() int64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *MetricRequest) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type SaveMetricResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResultJSON []byte `protobuf:"bytes,1,opt,name=resultJSON,proto3" json:"resultJSON,omitempty"`
}

func (x *SaveMetricResponse) Reset() {
	*x = SaveMetricResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_scraper_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveMetricResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveMetricResponse) ProtoMessage() {}

func (x *SaveMetricResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveMetricResponse.ProtoReflect.Descriptor instead.
func (*SaveMetricResponse) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{1}
}

func (x *SaveMetricResponse) GetResultJSON() []byte {
	if x != nil {
		return x.ResultJSON
	}
	return nil
}

var File_proto_scraper_proto protoreflect.FileDescriptor

var file_proto_scraper_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x63, 0x72, 0x61, 0x70, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x73, 0x63, 0x72, 0x61, 0x70, 0x65, 0x72, 0x22, 0x61,
	0x0a, 0x0d, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12,
	0x14, 0x0a, 0x05, 0x4d, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x4d, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x44, 0x65, 0x6c, 0x74, 0x61, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x44, 0x65, 0x6c, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x22, 0x34, 0x0a, 0x12, 0x53, 0x61, 0x76, 0x65, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x4a, 0x53, 0x4f, 0x4e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x4a, 0x53, 0x4f, 0x4e, 0x32, 0x54, 0x0a, 0x07, 0x4d, 0x65, 0x74, 0x72, 0x69,
	0x63, 0x73, 0x12, 0x49, 0x0a, 0x12, 0x53, 0x61, 0x76, 0x65, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63,
	0x46, 0x72, 0x6f, 0x6d, 0x4a, 0x53, 0x4f, 0x4e, 0x12, 0x16, 0x2e, 0x73, 0x63, 0x72, 0x61, 0x70,
	0x65, 0x72, 0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1b, 0x2e, 0x73, 0x63, 0x72, 0x61, 0x70, 0x65, 0x72, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x4d,
	0x65, 0x74, 0x72, 0x69, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x1e, 0x5a,
	0x1c, 0x79, 0x61, 0x6e, 0x64, 0x65, 0x78, 0x2d, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x2d,
	0x73, 0x63, 0x72, 0x61, 0x70, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_scraper_proto_rawDescOnce sync.Once
	file_proto_scraper_proto_rawDescData = file_proto_scraper_proto_rawDesc
)

func file_proto_scraper_proto_rawDescGZIP() []byte {
	file_proto_scraper_proto_rawDescOnce.Do(func() {
		file_proto_scraper_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_scraper_proto_rawDescData)
	})
	return file_proto_scraper_proto_rawDescData
}

var file_proto_scraper_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_scraper_proto_goTypes = []interface{}{
	(*MetricRequest)(nil),      // 0: scraper.MetricRequest
	(*SaveMetricResponse)(nil), // 1: scraper.SaveMetricResponse
}
var file_proto_scraper_proto_depIdxs = []int32{
	0, // 0: scraper.Metrics.SaveMetricFromJSON:input_type -> scraper.MetricRequest
	1, // 1: scraper.Metrics.SaveMetricFromJSON:output_type -> scraper.SaveMetricResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_scraper_proto_init() }
func file_proto_scraper_proto_init() {
	if File_proto_scraper_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_scraper_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetricRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_scraper_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveMetricResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_scraper_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_scraper_proto_goTypes,
		DependencyIndexes: file_proto_scraper_proto_depIdxs,
		MessageInfos:      file_proto_scraper_proto_msgTypes,
	}.Build()
	File_proto_scraper_proto = out.File
	file_proto_scraper_proto_rawDesc = nil
	file_proto_scraper_proto_goTypes = nil
	file_proto_scraper_proto_depIdxs = nil
}
